[package]
name = "serial-monitor"
description = "Simple Arduino Serial Monitor"
authors = ["Robin Schroer <git@sulami.xyz>"]
version = "0.1.0"
edition = "2021"

[dependencies]
serial-unix = "0.4"
serial-core = "0.4"
clap = {version = "3.1", features = ["derive"]}
